### ISSUE TITLE
Stuck Notification

### ISSUE THREAD

**Issue by satyambaba** [Blueforcer/awtrix3#334]
# Bug report

## Describe the bug

Once I send a notification with hold: true in the payload, then I dismiss the notification. After this, any notification I send gets stuck indefinitely even with hold: false and duration: 10. I have to manually dismiss these notifications. The intended behavior is that the notification should be displayed only for 10 seconds if duration is 10 and hold is false. Once I reboot, the issue gets resolved.

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: v0.88

## To Reproduce

1. Send a notification with hold: true in the payload
2. Dismiss the notification
3. Send a notification with hold: false and duration: 10

## Expected behavior

The intended behavior is that the notification should be displayed only for 10 seconds if duration is 10 and hold is false.

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment]
i catn reproduces it, works like it should

**Comment by satyambaba** [comment]
> i catn reproduces it, works like it should

Thanks for your response. It is still happening with me. Please let me know if you need any additional info in order to understand the issue better.

**Comment by Blueforcer** [comment]
Back to this issue.
Does it still exist in the latest firmware?

**Comment by satyambaba** [comment]
> Back to this issue. Does it still exist in the latest firmware?

It has been resolved in the latest firmware, you may close this issue. Thanks for your help.
