### ISSUE TITLE
Error connecting to wlan with special char in ssid [BUG]

### ISSUE THREAD

**Issue by fuNSA** [Blueforcer/awtrix3#360]
# Bug report

Hello

I have trouble connecting my Ulanzi Pixel Clock with AWTRIX-Light 0.90 to my wlan network. I think this is caused by an "&" in my ssid. I testet it on another network without special chars in the ssid and it worked fine.

**Comment by fuNSA** [comment]
Yes, that's possible. My password for the standard network has 20 characters, the guest password has 12.

**Comment by cherzog** [comment]
Sorry, my mistake. An incorrect FritzBox configuration was responsible for new devices not being included in the WLAN.

**Comment by Blueforcer** [comment]
Does this issue still exists? Otherwise please close this issue
