### ISSUE TITLE
No Sound[BUG]

### ISSUE THREAD

**Issue by dl1ekm** [Blueforcer/awtrix3#457]
# Bug report

## Describe the bug
I installed the default Ulanzi binary V0.91 on this board and used the hardware-description to wire my own Awtrix panel. All is working using the defautl Ulanzi/ESP ports - buttons, light, sensors... but not the buzzer. It should be connected to GPIO15 - but even with my scope I see nothing here.

## Additional information

- Devices involved:
  - Model: ESP 32 Board with Matrix-Panel from Ali Express (mode 2)
  - AWTRIX-LIGHT version: [ v.091 ]

## To Reproduce

I put a custom app in the custom app folder displaying some text. Additionally I set the parameter "sound" : "starwars" in the json. I uploaded a sample melodie (from internet and checked with the given links), saved as starwars.txt.

## Expected behavior
Shouldn't I hear the sound while text is scrolling?

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by dl1ekm** [comment]
Why completed?

**Comment by Blueforcer** [comment]
Because at there was no single description of your problem. 
Now it's edited

**Comment by Blueforcer** [comment]
What firmware youre using?

**Comment by Blueforcer** [comment]
is this fixed?

**Comment by dl1ekm** [comment]
I haven given up with 0.94 and desolded the speaker :-) Last idea - is an ACTIVE buzzer (just needs 3,3V) or a passive one (controlled with PWM) required? My current buzzer is only "clicking" - in the past  (older FW) I tested both variants without success. Should I give it again a try?

**Comment by Blueforcer** [comment]
Ulanzi firmware only supports a passive piezo buzzer.

Awtrix2_upgrade only supports dfplayer. But this firmware is made for users of the old awtrix so they don't need to rebuild
