### ISSUE TITLE
[FEATURE REQUEST] For use system time

### ISSUE THREAD

**Issue by Jeandhom** [Blueforcer/awtrix3#506]
Hello,
Would it be possible to provide a variable representing the system time in order to be able to use it in customApps or notifications?
Thanks.

**Comment by Blueforcer** [comment]
The meaning behind this is not quite clear to me. You are already sending this from an external system that can provide a time itself.

**Comment by Jeandhom** [comment]
Thanks for your answer.

Yes, but it was to avoid having to do it every minute.
{"text":"$time - Blablabla", "duration":300}

**Comment by Jeandhom** [comment]
Never mind but thanks for watching
