### ISSUE TITLE
[FEATURE REQUEST] Sensor value with corner indicators?

### ISSUE THREAD

**Issue by alfureu** [Blueforcer/awtrix3#508]
# Feature Request

### Is your feature request related to a problem?

So I have a sensor, which also has a trendline defined, and it will be useful to have a sensor + trendline corner indicator blueprint

### Describe the solution / feature you'd like

Have the icon, the value defined, and be able to define the upper-middle-bottom corner for trendlines, with colours for ranges of values (defined also by the user)

### Describe alternatives you've considered

Adding arrows to the numerical value, but it is not supported by Awtrix fonts

### Additional context

N/A

**Comment by Blueforcer** [comment]
Blueprints all has nothing to do with the Firmware. You should ask this to the discord community if someone can create it.
