### ISSUE TITLE
The € sign is not displayed correctly in 0.95

### ISSUE THREAD

**Issue by mrjeschke** [Blueforcer/awtrix3#509]
The € sign is not displayed correctly in 0.95
In der Version 0.95 wird das € zeichen nicht richtig angezeigt.
Neu flashen (inklusive löschen) hat nicht geholfen.
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version:0.95

![awtrix](https://github.com/Blueforcer/awtrix3/assets/71946366/aa7babdb-ce41-4524-8128-44ce99b24f80)

**Comment by Blueforcer** [comment]
Working on it
