### ISSUE TITLE
Disable Battery Display within dev.json

### ISSUE THREAD

**Issue by fidoriel** [Blueforcer/awtrix3#510]
It would be great to disable the battery level without mqtt with a simple setting in `dev.json`. So that sending `[{"name":"bat","show":false}]` to `/app` is not necessary anymore.

**Comment by MrHollowPS** [comment]
You can disable the battery thing from within the clock settings. hold the middle button on the clock then navigate until you reach the Apps menu and in there battery off.

**Comment by Blueforcer** [comment]
> It would be great to disable the battery level without mqtt with a simple setting in `dev.json`. So that sending `[{"name":"bat","show":false}]` to `/app` is not necessary anymore.
> 

this API doesn't exist in the documentation, and shouldn't be used.

you can use the official App or API to turn it off permanently

**Comment by fidoriel** [comment]
> You can disable the battery thing from within the clock settings. hold the middle button on the clock then navigate until you reach the Apps menu and in there battery off.

Why is this not documented?

**Comment by fidoriel** [comment]
Did not expect to find it there :)
