### ISSUE TITLE
Icon Uploader missing [BUG]

### ISSUE THREAD

**Issue by appinator** [Blueforcer/awtrix3#511]
After updating to 0.95 i'm missing the "Icons" Menu on the webinterface. I tried different browsers and clients (Mac; Windows, iPhone) and cleared my cache.

![Screenshot 2024-03-14 162340](https://github.com/Blueforcer/awtrix3/assets/2093674/5464c942-400c-49cf-90a5-5c464b88dddf)

**Comment by Blueforcer** [comment]
Remove the DoNotTouch.json and reboot awtrix. You'll need to setup your Mqtt and time settings again.

**Comment by appinator** [comment]
Thanks. Did the trick.
