### ISSUE TITLE
[BUG] Not reaction for rainbow text option in MQTT service

### ISSUE THREAD

**Issue by zerofull56** [Blueforcer/awtrix3#512]
# Bug report

## Describe the bug

If I add a line with "rainbow":"false" to the script in HA for send a message to the clock, the text will be colored.

## Additional information

- Devices involved:
  - Model: Awtrix 2
  - awtrix3 version: 0.96
## To Reproduce

Send for MQTT service in HA:
"text":"Hello!",
"rainbow":"false"

**Comment by Blueforcer** [comment]
You need to send it as Boolean value not as string

"rainbow":false

**Comment by zerofull56** [comment]
Oops, it's my fault. I using template for this script, and input_boolean.yml for "rainbow", who send "on" and "off" instead "true" and "false"... May be i need use some soft switch instead boolean. Thanks for explanation, now, can close the issue.
