### ISSUE TITLE
[BUG] unauthorized error - Icon Designer

### ISSUE THREAD

**Issue by hugihug** [Blueforcer/awtrix3#514]
# Bug report

## Describe the bug
It ist not possible to save an created icon to the AWTRIX device if an user and password is set.

## Additional information
Dialog Error unauthorized appears

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: 0.96

**Comment by Blueforcer** [comment]
Please be more detailed

**Comment by hugihug** [comment]
I designed an icon with the icon editor and try to save it with "Save to AWTRIX" after entering a name.
This results in Dialog box which says ERROR UNAUTHORIZED.
 In the device a user and a password is set. So I assumed that there is an issue with the authorisation.

**Comment by Blueforcer** [comment]
App update is in preview.
