### ISSUE TITLE
The time display format cannot be changed.[BUG]

### ISSUE THREAD

**Issue by bladeback** [Blueforcer/awtrix3#524]
When I change the time format to HH:MM:SS in the "on screen menu" (screen down)
 @@
![1711980148334](https://github.com/Blueforcer/awtrix3/assets/18068966/2205ad0c-d08f-4b53-9fc1-db8050f46073)

it still shows me only HH:MM and the day of the month in a red frame on the left. How to change it to show only time with seconds?
![1711979909442](https://github.com/Blueforcer/awtrix3/assets/18068966/ac006bf2-771c-4b58-8d02-e11b0a9d8f22)

I would like to display the clock like this:
![Snímek obrazovky 2024-04-01 155952](https://github.com/Blueforcer/awtrix3/assets/18068966/4d89e90c-3f43-424f-8a3a-70b5f05292c5)

**Comment by Blueforcer** [comment]
As you can see, this format can't fit together with the calendar icon. Change the time mode to remove it. You can to this with the /settings API or with the awtrix app

**Comment by bladeback** [comment]
> As you can see, this format can't fit together with the calendar icon. Change the time mode to remove it. You can to this with the /settings API or with the awtrix app

I understand that it won't fit there, I don't need the calendar icon.
How do I do this via "settings/API" please?

**Comment by dedelastuce** [comment]
Hi I m in the same situation, I would like to remove the calendar icon to show full time (like old awtrix). Is it possible?
I tried to change time format it doesn't work calendar icon is still here

**Comment by Blueforcer** [comment]
> Hi I m in the same situation, I would like to remove the calendar icon to show full time (like old awtrix). Is it possible?
> I tried to change time format it doesn't work calendar icon is still here

Both methods are described above.

**Comment by on4ami** [comment]
Can someone tell me what settings requires the modification. I tried TMODE but does not solve

**Comment by Blueforcer** [comment]
> Can someone tell me what settings requires the modification. I tried TMODE but does not solve

Just some line under TMODE : 
TFORMAT |  Time format for the TimeApp.

**Comment by on4ami** [comment]
Hereby my settings. Calendar in front.

"MATP": true,
    "ABRI": false,
    "BRI": 125,
    "ATRANS": true,
    "TCOL": 16776954,
    "TEFF": 1,
    "TSPEED": 300,
    "ATIME": 5,
    "TMODE": 1,
    "CHCOL": 16711680,
    "CTCOL": 0,
    "CBCOL": 16777215,
    "TFORMAT": "%H:%M:%S",
    "DFORMAT": "%d/%m/%y",
    "SOM": true,
    "CEL": true,
    "BLOCKN": false,
    "MAT": 0,
    "SOUND": true,
    "GAMMA": 1.899999976,
    "UPPERCASE": true,
    "CCORRECTION": "#000000",
    "CTEMP": "#000000",
    "WD": true,
    "WDCA": 16777215,
    "WDCI": 6710886,
    "TIME_COL": 0,
    "DATE_COL": 0,
    "HUM_COL": 0,
    "TEMP_COL": 0,
    "BAT_COL": 0,
    "SSPEED": 100,
    "TIM": true,
    "DAT": false,
    "HUM": false,
    "TEMP": false,
    "BAT": false,
    "VOL": 25,
    "OVERLAY": "clear"
![awtrix](https://github.com/Blueforcer/awtrix3/assets/35608765/4dfe0cdf-9aa4-4916-b6a5-68a1d361d442)

**Comment by Blueforcer** [comment]
You cannot display this time format because it doesn't fit together with the calendar. Disable the calendar or change the time format to something without seconds.

**Comment by hsauce** [comment]
Not sure why the default time format was changed without an easy to change it back to what it used to be. Now you need to know how to use the terminal or a command line prompt app (or pay for the mobile app).

Anyways here's the curl command you can use to reset it back to what it used to be. Make sure you replace `<ip-address>` with your clock's address.

```shell
curl --location 'http://<ip-address>/api/settings' \
--header 'Content-Type: application/json' \
--data '{
    "TMODE": 0
}'
```
