### ISSUE TITLE
Unable to update Firmware [BUG]

### ISSUE THREAD

**Issue by BenAhrdt** [Blueforcer/awtrix3#525]
# Bug report
Unable to update firmware.

## Describe the bug

I like to update firmware.
actual 0.94

if i click on update:

The Text: "ERR CNCT" is shown.

**Comment by modem7** [comment]
Same here with 0.96

**Comment by gittjoel** [comment]
did update to 0.96 in WebIf. --> OK. But if I try on the AWTRIX same error: "ERR CNCT" is shown.
Display shuts off, no reaktion anymore. 
Only switch off and on reanimates the AWTRIX.

**Comment by plutosherry** [comment]
also same here with 0.96

**Comment by Blueforcer** [comment]
I have now spent 3 hours trying to locate the error.
Unfortunately without success. Github refuses the connection.
Maybe someone else can try it?

**Comment by modem7** [comment]
> I have now spent 3 hours trying to locate the error. Unfortunately without success. Github refuses the connection. Maybe someone else can try it?

I'm wondering if it's because you're using the raw link rather than the CDN? I suspect they probably rate limit the raw connection. 

Maybe try https://github.com/Blueforcer/awtrix3/blob/main/docs/ulanzi_flasher/firmware/firmware.bin and https://github.com/Blueforcer/awtrix3/blob/main/docs/awtrix2_flasher/firmware/firmware.bin instead in https://github.com/Blueforcer/awtrix3/blob/main/src/UpdateManager.cpp?

**Comment by Blueforcer** [comment]
Both is not working.
https://github.com/Blueforcer/awtrix3/blob/main/docs/ulanzi_flasher/firmware/firmware.bin 
doesnt point directly to the blob file.

https://github.com/Blueforcer/awtrix3/raw/main/docs/ulanzi_flasher/firmware/firmware.bin
Also doesnt work

Using the API would require to expose my github token in the sourcecode.

**Comment by modem7** [comment]
> Both is not working. https://github.com/Blueforcer/awtrix3/blob/main/docs/ulanzi_flasher/firmware/firmware.bin doesnt point directly to the blob file.

That was my concern, I'm wondering if adding it to releases will allow you to reference the blob itself via CDN (it seems from a very quick google search that this is the only real way of doing it from my understanding).

> Using the API would require to expose my github token in the sourcecode.

Looks like for version, you don't need to utilise the token.

```console
curl --silent "https://api.github.com/repos/Blueforcer/awtrix3/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
0.96
```

**Comment by JC-23** [comment]
The issue lies with the outdated DigiCert Root certificate used. Updating to current G2 Root solves the issue and firmware update checks work again.

**Comment by BenAhrdt** [comment]
What i have to do?

**Comment by Blueforcer** [comment]
> What i have to do?

Wait for the update.
However, this will only come into play in the update after next. The next update will have to be done via the app via USB or via the web interface anyway.

**Comment by BenAhrdt** [comment]
OK, what is the next update? And i go to the web interface and update from there?
This works?

**Comment by Blueforcer** [comment]
Next update will be 0.97?

**Comment by BenAhrdt** [comment]
wich file i have to download for?

**Comment by Blueforcer** [comment]
> wich file i have to download for?

For what?

**Comment by BenAhrdt** [comment]
to update firmware via webpaghe?
![image](https://github.com/Blueforcer/awtrix3/assets/92173565/559f41ad-5b23-4050-b1cd-9c85781177d6)

**Comment by Blueforcer** [comment]
What do you want to update?
Current firmware is 0.96. you can find all versions in the GitHub release page

**Comment by BenAhrdt** [comment]
Yes, i mean... if the 0.97 is available.
Where can i find the file?
The Update from device dies not work.

**Comment by modem7** [comment]
> Yes, i mean... if the 0.97 is available.
> Where can i find the file?
> The Update from device dies not work.

In the releases section of the repo.

**Comment by BenAhrdt** [comment]
This file: (other version)
![image](https://github.com/Blueforcer/awtrix3/assets/92173565/67c35f7f-ce3e-42e1-995a-813277b21218)

**Comment by BenAhrdt** [comment]
when the 0.97 comes up?

**Comment by Blueforcer** [comment]
> when the 0.97 comes up?

idk, But at the moment it doesn't matter, because the ondevice update will only work from 0.98 anyway. 0.97. 0.97 must be updated in a different way, via webinterface, USB or App

**Comment by BenAhrdt** [comment]
ok.i updated the device to 0.96

**Comment by Njdfg** [comment]
Any news when a Update is ready?

**Comment by beta-j** [comment]
If you're looking for a temporary workaround to manually update Awtrix on your Ulanzi display, here's a quick summary of what you need to do:

1. First determine the IP address of your Ulanzi display 
2. Go to [https://github.com/Blueforcer/awtrix3/releases](https://github.com/Blueforcer/awtrix3/releases) and download the .bin file for the latest firmware version (eg. **ulanzi_TC001_0.96.bin**)
3. Go to http://[ULANZI_IP]/update
4. Under `Firmware`, click on `Choose File` and select the *.bin file you downloaded in Step 2.
5. Click on `Update Firmware` and wait...
6. ...Ulanzi display will automatically reboot with the updated firmware after a minute or two.
