### ISSUE TITLE
Save dummies!

### ISSUE THREAD

**Issue by zarss** [Blueforcer/awtrix3#528]
Hi. Sorry of me being a little bit negative, but currently I feel myself a biggest idiot on planet Earth. 
Long version: all I wanted originally was to display a temperature reading from a ESPHome based sensor to 8x32 pixel display. I could not found a quick solution, but my search led to Awtrix 3. After a quick look, noticed that it is mentioning to work with Home Assistant. Decided to go ahead with the hope of figuring it out quickly. I was very wrong, you can get all sorts of complicated stuff examples, a lot of unnecessary things, but missing two very important things for idiots like me. One of them is - how to make your own apps and what to do with the flows. 
  Sorry again, my intention is not hurt anybody feelings (I have brought Awtrix app to give my support), but I feel very bad when cannot figure out simple things. Thank you for reading this.

**Comment by Blueforcer** [comment]
Explaining Homeassistant has nothing to do with AWTRIX. You can use any other system, even a commandline if you like.
AWTRIX just provides an API with is explained deeply. 
However, how you set this up and send it to awtrix is up to you.
