### ISSUE TITLE
[FEATURE REQUEST] Like Awtrix AnotherTime plugin mode

### ISSUE THREAD

**Issue by bitxeno** [Blueforcer/awtrix3#532]
# Feature Request

### Is your feature request related to a problem?

No.

### Describe the solution / feature you'd like

Can awtrix3 achieve the same effect as the  awtrix AnotherTime plugin, showing a fixed time on one side while retrieving additional information on the other?

### Additional [context]

![VID_20240416_110159](https://github.com/Blueforcer/awtrix3/assets/137328844/59cea8d1-d192-47c6-8d12-5badd15522de)

**Comment by Blueforcer** [comment]
No, there are custom apps for that. 
If I start to code everything natively, then firstly there is no end to it and secondly the memory is empty very quickly.
