### ISSUE TITLE
Doc issue on switch sample

### ISSUE THREAD

**Issue by Brouno** [Blueforcer/awtrix3#534]
Small case typo in doc here :

[Switch to Specific App](https://blueforcer.github.io/awtrix3/#/api?id=switch-to-specific-app)

The sample show "payload/Body" as {"name":"time"}
which is not working with 1st char lowercase

Should be {"name":"Time"}

Just after the built-in apps list are correct btw

**Comment by Blueforcer** [comment]
Done, thx
