### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by ETGermany** [Blueforcer/awtrix3#536]
# Feature Request

### Is your feature request related to a problem?

The available file system is much too small

### Describe the solution / feature you'd like

I need much more memory for icons, apps, etc.

### Describe alternatives you've considered

The flash memory of TC001 is 16 MB. Why is there only 60 kiB for the file system? To use my icons, I deleted the DoNotTouch file, Ulanzi still works so far.

### Additional context

<img width="729" alt="Ulanzi Filesystem voll 21-04-2024_11-43-40" src="https://github.com/Blueforcer/awtrix3/assets/132834418/2ed5844c-0cc7-4f08-9f14-c10e74423c58">

**Comment by eku** [comment]
According to the [partitioning](https://github.com/Blueforcer/awtrix3/blob/main/awtrix_partition.csv)  SPIFFS is larger than 1 MB.

**Comment by ETGermany** [comment]
That may be true, but my illustration shows something else. Perhaps partitioning is not working?

**Comment by Blueforcer** [comment]
Dont use the original ulanzi update function. They using another weird partition table. 
If you flash it with the webflasher (with full erase) you have 1360 KB free..

**Comment by ETGermany** [comment]
I had already given up with the web flasher because I was constantly getting an error message:

<img width="309" alt="Fehlermeldung" src="https://github.com/Blueforcer/awtrix3/assets/132834418/60919639-6485-409f-bd93-12e8ad37c4a4">

The EspHomeFlasher I used also deleted beforehand and output this information:

<img width="266" alt="FlasherInfo" src="https://github.com/Blueforcer/awtrix3/assets/132834418/7cea4246-05aa-445e-923d-842fc929c906">

Due to your information I have now tried again, after 5 error messages it finally worked!

<img width="222" alt="Speicherplatz" src="https://github.com/Blueforcer/awtrix3/assets/132834418/33b5593a-8a97-4d92-a161-787e0d91a57a">

Great - now there is storage space.
Thank you very much!

**Comment by MJHeijster** [comment]
Damn, I've been having the same issue while flashing... I have deleted a lot of icons because of the storage problem...I'll try flashing it again, but is it possible to use network storage for icons? A nas can help?

**Comment by Blueforcer** [comment]
> but is it possible to use network storage for icons? A nas can help?

Thats not possible,
