### ISSUE TITLE
Broker Mosquitto / awtrix + OpenDtu

### ISSUE THREAD

**Issue by steflp** [Blueforcer/awtrix3#545]
Hi ,  
Ive openDTU with solar panel. 
I want to send data topic from DTU to topic awtrix .
I  Dont use Home Assistant so I must find a solution homemade , i suppose.

My topics in Mqtt  : 
![image](https://github.com/Blueforcer/awtrix3/assets/3442544/fcad0f1c-945f-4314-97ae-f0aa4f98be51)

Can someone help / explain ? 

Many  Thanks

**Comment by PowerWiesel** [comment]
use node-red as middle man

![Bildschirmfoto vom 2024-05-02 18-12-11](https://github.com/Blueforcer/awtrix3/assets/11167590/0b4218e2-7846-4b9d-a00c-783d33f73851)

my function node:

`var value = Math.round( msg.payload );
var unit = "Wh";


msg.payload = {  
    "text": value + '' + unit,
    "icon": "power_gen", 
    "repeat": 2, 
    "pushIcon": 0 
};

node.status({ fill: 'green', shape: 'ring', text: value + ' ' + unit});

return msg;`

**Comment by steflp** [comment]
Hello,
I install  node red  : it 's OK
( I  dont know really how it s work  )  
I create  Mqtt In with my solar/ac/yieldday
I use your function (???) 
I create Mqtt out 

But after i dont know realyy how to do ....
![image](https://github.com/Blueforcer/awtrix3/assets/3442544/c88d08cf-7fa9-4e2a-b88c-ad1a631551f1)

**Comment by Blueforcer** [comment]
You should join my discord for such questions. There are many users who might help you.
I think GitHub issue is not the right place for that.

**Comment by steflp** [comment]
ok  ;)   sorry  ...
