### ISSUE TITLE
[FEATURE REQUEST] More Options for Time Input (GPS, Atomic 60Khz, ect;)

### ISSUE THREAD

**Issue by 2015corvettec7** [Blueforcer/awtrix3#548]
# Feature Request

### Is your feature request related to a problem?

AWTRIX 3 is amazing, when it's on a Wi-Fi network. But sometimes I'd like to deploy one where a Wi-Fi network isn't available or reliable.

### Describe the solution / feature you'd like

AWTRIX should have the capability to take an input from a UBlox-based GPS Module to get accurate time data without an Internet connection. Another readily available GPIO-pin compatible option I've seen are GPIO add-on modules that receive the 60khz Atomic clock signal. There are already Arduino sketches out there that can make an offline NTP Server using one of these modules and an ESP32, so the concept is already proven.

### Describe alternatives you've considered.

I've actually used one of these previously mentioned Arduino Sketches to build my own offline NTP Server for a couple AWTRIX 3 based clocks I'm making that will be living in a workshop on a different part of my family's property where we do not have Wi-Fi installed. This solution works really well in my testing, however it would be nice if this functionality was built directly into AWTRIX 3 so that one wouldn't need an entire second ESP32 just to bring in the time data.

### Additional context

The Arduino Sketch uses the ESP32's Wi-Fi chipset in AP mode, so connecting the clocks to it is as easy as punching in the pre-configured password and entering the NTP Server's local IP address into AWTRIX 3's "Time" tab.

**Comment by Blueforcer** [comment]
That makes no sense to me, without wifi awtrix is useless, its a smarthome companion.
