### ISSUE TITLE
Awtrix 0.96 & 0.94 on two Ulanzi TC001 reboot up to two times a day

### ISSUE THREAD

**Issue by UCaGk** [Blueforcer/awtrix3#553]
# Bug report
I use two different Awtrix versions on two Ulanzi TC0001 clocks.
The clocks are under control of Home Assistant MQTT, each clock only shows time and on different events ICON, Sound and Text, but mostly time in format HH:MM:SS or HH:MM in color white, brithness 1-20, depending on some events.
Every clock reboots at a purely random time, without an event, just like that. Sometimes a colored dot appears, sometimes part of the matrix turns bright white, then the firmware restarts and clock run again. 
Looks like the display "freeze" (sometimes a few leds flicker) and a watchdog reboots...
Both clocks has accumulator removed, some changes to pcb and a 3.3V stepdown regulator.
I'm not sure if the clocks reboot more than 2 times, because I'm not sitting in front of them the whole day :-)

Devices involved:
  - Model: 2x Ulanzi (TC001)
  - awtrix3 version:  v0.94 & v0.96

 - not possible, because this happens randomly

 - It would be nice to know if there ist problem in software, if so, a new version would be great :-)

**Comment by Blueforcer** [comment]
Check the RAM usage.
If your using the Homeassistant discovery entities very often the RAM usage increases because of a memory leak in the used library.
Switch to raw MQTT API commands and you're fine.

**Comment by UCaGk** [comment]
Oh, that was fast :-)

Sorry for my misunderstanding, but what do you mean with "Switch to raw MQTT API commands"

This is a code snippet:  Is this raw MQTT ? If not, how looks it like ?

`
      - alias: Zeitformat HH:MM Hell
        service: mqtt.publish
        metadata: {}
        data:
          qos: 0
          retain: false
          topic: UhrWZ/settings
          payload: >-
            {    "TIME_COL": [255,255,255],  "WD": false,  
            "TFORMAT": "%H:%M",   "TMODE": 0, "ABRI": false,  "BRI":
            20 }
        enabled: true
`

**Comment by Blueforcer** [comment]
Thats correct. 
i mean using the awtrix entities like
![image](https://github.com/Blueforcer/awtrix3/assets/31169771/f887a3cb-a8ed-4313-8059-3d62fa3ad6fc)

**Comment by Jeandhom** [comment]
> if the clocks reboot more than 2 times, because I'm not sitting in front of them the whole day

You can monitor the device's uptime.

![Capture d’écran du 2024-05-13 23-28-32](https://github.com/Blueforcer/awtrix3/assets/49077193/ab405286-955e-45c0-ba79-02a4726f0a53)

**Comment by Blueforcer** [comment]
> Not sure how fast the free memory space shrinks.

Just use Homeassistants history, you can see the ram over time in a graph 📉

**Comment by UCaGk** [comment]
Thanks for the hints, i made some entities, here are the results.

The other clock looks similar, only the battery history is a line at 100%.
It`s a strange battery plot, but the uptime only restarts at ~ 4:30 h this morning. (I reboot the clock at 3 am every day)
If there is a power problem the uptime counter should restart more than once in this history, right ?
I think it's not a memory problem.

![grafik](https://github.com/Blueforcer/awtrix3/assets/121627696/aa362c3b-624a-4884-83d1-8a7039981e19)
![grafik](https://github.com/Blueforcer/awtrix3/assets/121627696/5d0366be-42f1-4961-8e58-095fa89894fe)
![grafik](https://github.com/Blueforcer/awtrix3/assets/121627696/1416efd6-c14b-4320-bcc9-0b01eefe34c7)

**Comment by Blueforcer** [comment]
I assume that something is wrong with the power supply.
When the display freezes but some leds flickers, its not a software issue.

**Comment by UCaGk** [comment]
Thanks for your help, I was also worried that it was the power supply, I was already thinking about whether I would only use the RGB LEDs with housing from the Ulanzi and replace the hardware with a simple ESP, will see.

**Comment by Blueforcer** [comment]
40kb is too low. Check wich automation cause the memory drop

**Comment by UCaGk** [comment]
Sorry for writing again, maybe it helps, if there is a bug.
After a better look onto the clock I saw that the pixel do not flicker. Often there is a dot on the uper left, the clock is frozen and about 10 s the colored AWTRIX - IP - MQTT startup comes up, after that the clock is running like before, if display was HH:MM 
than ist shows HH:MM, was the display HH:MM:SS before, HH:MM:SS is shown and everything look like before.
Situation is like before, memory always >110kb

**Comment by Blueforcer** [comment]
You should read the whole issue. Don't control the HA entities often, instead use raw mqtt commands

**Comment by Blueforcer** [comment]
Did you find the error?

**Comment by UCaGk** [comment]
Hello Stephan, thanks for asking.
The last few weeks have been a bit stressful, I haven't had time, but I'm currently checking the voltages and wanted to solder a capacitor to the 3.3V voltage converter in case of short-term current spikes.
In the meantime, I also had the situation where the clock restarted and switched to AP mode, and once it didn't start automatically at all.

**Comment by UCaGk** [comment]
Hello Stephan, thanks for asking.
The last few weeks have been a bit stressful, I haven't had time, but I'm currently checking the voltages and wanted to solder a capacitor to the 3.3V voltage converter in case of short-term current spikes.
In the meantime, I also had the situation where the clock restarted and switched to AP mode, and once it didn't start automatically at all.
![grafik](https://github.com/Blueforcer/awtrix3/assets/121627696/0e4d4c6a-ad5f-4609-b336-931d4aa07ed1)

After adding the capacitor to both clocks, things getting more and more strange...
Before adding the capacitor, the "uptime counter" only increases to about 16000 (see diagram)
After adding the capacitor, the counter continues to increase without resetting at about 16000 (see diagram after 12.6./9:00) ????
What is the bit size of the uptime counter?

**Comment by UCaGk** [comment]
Update after one day running with the capacitor the clock didn't reset, the uptime value increase.
But, sometimes the display switch off (fully dark) for about 1 sec, after that the display switch on again as if there was nothing, without restarting (uptime still increasing). Think this is the reason why the voltage of DC-DC stepdown regulator without cap has a voltage spike the restarts the esp inside. 
Now it would be nice to know why the display switch off for a second ?

![grafik](https://github.com/Blueforcer/awtrix3/assets/121627696/7472e55b-0240-473d-8650-f8e985058782)

**Comment by Blueforcer** [comment]
There is no software automation to switch off the display.
Maybe one of your automation send the power request.
But for hardware related things, this repo isnt the right place. unfortunately i can't help if someone modifies the hardware. i only do software :)
I recommend you join the discrod, a few have done it there. And there's also the problem that the Ulanzi will eventually switch itself off after the mod.

**Comment by vogtmh** [comment]
I already mentioned my "RAM problem" in another issue, but it might apply here as well:

I had a similar issue, could successfully reproduce and fix it. Long story short: I didn't know about the blink or fade functionality included in Awtrix, so I used a loop in a Home Assistant automation to turn the lights on and off every second, using a custom component which defaulted to QoS of 1. 

The solution was to remove the custom component and use the built-in mqtt.publish instead, defining a QoS of 0 for all commands. I also replaced the loops with single mqtt.publish commands, where I set the indicators to blink or fade. 

All problems are gone since then. Thanks for this AWesome custom firmware! :)

**Comment by eku** [comment]
I observed the following yesterday.

During the display of a custom app, its value was changed as a result of an update via MQTT. The value of the display still changed, but it was no longer switched to the next app. The software was frozen and was forced to restart by the watchdog.

**Comment by UCaGk** [comment]
FYI
After a few days of using the capacitor, the operating time no longer resets.
What I see is that the clock display sometimes "turns off" for about 1 second. One time, the top left LED was green while the rest of the display was black. After the second, the display turns on, the green dot is gone, and the time continues as if nothing happened. The memory remains almost constant except for the usual fluctuations.
Because this short "turn off" is very rare and the clock does not restart, I am fine with it.

**Comment by popy2k14** [comment]
@UCaGk I am the guy which posted the battery removal guide on reddit. Also replaced the power supply with an 3V3 converter. I am running https://github.com/lubeda/EspHoMaTriXv2 (complete other software).

And you know what...

I have the exact same issue that the clock reboots a few times a day (sometimes with the first led/dot in the corner).
Programmed my yaml the way, so it resumes where it was, so no big deal for me ... But also annoyed me since I have those clocks. I have two of them, and one is worse than the other. Sadly had no time to dig deeper from an HW PoV.

Interesting that an Cap solved the issue for you. 

So here are my questions:

Does this fix work for you also after using it longer?

Can you please tell us which value you have soldered into the device and exactly where? (Photo would be cool)

**Comment by UCaGk** [comment]
@popy2k14 
Nice to hear that i'm not alone with this problem, even this is not a nice problem.
And, is good to hear that is not a problem of the firmware, because we are using different once. In te past i also though to install EspHoMaTriX, but after your feedback i do not need to switch now.

It is exactly the same behavior, you discribe, with my two clocks. One clock reboots (not really a full reboot) raher rare, one reboot more often. With the caps it is not a full reboot, it is something like this: The display gets black for, not sure, about 2-3 seconds, sometimes there is a green dot in the upper left part of the display before it get black sometimes not. Because the second clock is in a really dark display mode, i'm not sure if the behavior is the same.
Before useing the caps the clocks made a full reboot with new connectiong to wifi.

Afteri made this changes it was and is ok for me, even if it would be better the clock would work without such "black-out features".

Have you ever thought about replacing the whole Ulanzi hardware by a simple esp connected to the display of the Ulanzi, and use the EspHoMaTriXv2 firmware with it ? This was something i thought about in the past.

**Comment by popy2k14** [comment]
@UCaGk yeah, i had those issues since i made my post on reddit back than: https://www.reddit.com/r/homeassistant/comments/131okf7/comment/jwudxjk/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Have you done your mod from my picture / guide?

I have now added an 1000µF / 10V cap on each clock directly on the ESP32 GND & VCC Pins (3V3 rail) and will see how it goes. Also activated the uptime sensor logging.

Yeah i have thought of ditching the original pcb board and just using an ESP32 (which i also have laying around).
But the ulantzi pcb has some features which i dont want to miss or replicate (ex.: the light sensor, buttons, ...).
Sure we can develop our own pcb, but hell yeah it always the same ... lack of time... :-)

If you think again to sitch to EspHoMaTriXv2, be aware that it has some bugs and is not that much maintained because lack of other devs. Dont get me wrong, lubeda and andrewjswan doing an amazing job!!!, but if you have other use cases than the devs (like me :-) ) you may face some bugs. Ex.: there is an looping bug which was not found up until now, where i just have made an workaround in my yaml for (some sort of wdt). But overall i am pretty happy with it. This here: https://github.com/lubeda/EspHoMaTriXv2/issues/245

Will keep you updated if my reboots of the ESP32 is gone.

**Comment by UCaGk** [comment]
@popy2k14 
I'm sorry, i forgot the position and value of the cap, it is also a 1000 uF, in my case a 35V because it was in my "junk box".
I put it on the 3,3V side of the converter.
Thought abot a second one on the 5V side.
And yes I made it from you pictures.

It would be nice too hear from you if the reboots are gone.
When finding time to replace the Ulanzi board and build my own hardware i will post it.

**Comment by popy2k14** [comment]
@UCaGk ok thx for confirming your used cap value, so i should see the same result.

If i had time i would make my own PCB (i am an HW engineer for ~20 years) but sadly dont have much time for that.
Would be nice if you share replacement hardware, if you find some time to make one :-)

But until that happens HUGHE thanks to bring this issue back to my attention and also post a workaround!!!
To be hohnest, i just forgot about it :-)
Really appreciate that!

If that also works for me, i will update my reddit post.

**Comment by Blueforcer** [comment]
I have direct contact to the Ulanzi hardware engineer. I will ask him how to Bypass the battery.

**Comment by popy2k14** [comment]
> I have direct contact to the Ulanzi hardware engineer. I will ask him how to Bypass the battery.

That would be awesome!!!!
Maybe he can share the circuit also, that would help a lot.

Thx

**Comment by UCaGk** [comment]
This would be the BEST SOLUTION ever !
Hope he could help.

Thanks Stephan !

**Comment by popy2k14** [comment]
Here are my results with the additional 1000µF/16V cap on the 3V3 rail.
Working as expected, and the ESP32 of the clocks are stable for an day now:

![image](https://github.com/user-attachments/assets/91f62e9f-8aac-456e-8f91-5685bf19fdae)

And yes, something is switching the matrix off/on. Also when the esp32 is stable now, the matrix sometimes glitches (black or bright dot in the top left corner for about 2-3 secs) like @UCaGk stated above also on my clocks. 

@Blueforcer 
Would be really nice if we can get help of the hw dev, whats going on here.

**Comment by popy2k14** [comment]
@eku thanks for the hint. the ESP restart is because "something" on the board is switching power on certain events.
This was mitigated and solved by adding an 3V3 capacitor + confirmed by @UCaGk and me.
Sure this feature would have helped to get a reset reason. In our case it probably would be something like brown out or power on reset.

As stated the esp is now stable, but not the LED matrix, which get's reset in an interval (sadly sometimes one led is at 100% white, when this happens).

So there mus be something on the PCB which triggers those events which we don't know or have investigated.

**Comment by eku** [comment]
> @eku thanks for the hint. the ESP restart is because "something" on the board is switching power on certain events.

As mentioned in my first comment here, I had observed a software (dead)lock that triggered the watchdog.

**Comment by popy2k14** [comment]
@eku sorry, missed that. Sure for software related issues, knowing why it restarted may help.

**Comment by popy2k14** [comment]
@Blueforcer any news from the hw engineer  of ulanzi tc001?

**Comment by Blueforcer** [comment]
> > @eku thanks for the hint. the ESP restart is because "something" on the board is switching power on certain events.
> 
> As mentioned in my first comment here, I had observed a software (dead)lock that triggered the watchdog.

but it also happens with other completely different firmwares. At the exact same time.

**Comment by popy2k14** [comment]
hi guys. Because the original reddit thread was archived, i have created an new one here: https://www.reddit.com/r/homeassistant/comments/1grzksj/ulanzi_tc001_always_on_mod_battery_removal/
with updated instructions.

**Comment by UCaGk** [comment]
@popy2k14 
👍 

Hope there will be some information on the “power problem” in the near future, from whoever,

**Comment by Blueforcer** [comment]
No message from Ulanzi so far. I think they used discord only for contacting me...

**Comment by popy2k14** [comment]
thx, for trying.
Maybe you get an answer.

As stated, for me two clocks are much more stable now with the added cap.

**Comment by UCaGk** [comment]
@popy2k14 
I added a second 1000uF cap to the input of the step down in both clocks.

![Caps](https://github.com/user-attachments/assets/5803ac83-7aa6-4b3d-9115-4f478d9a2661)

It's only been a few hours and I don't always check the clocks but it seems stable at the moment.
If you have a second cap in stock, it would be nice if you could plug it in too so we can get better stats :-)

It would be nice to have a method to catch the error without watching...

**Comment by UCaGk** [comment]
@popy2k14 
Good to hear you have some spare parts !

Yes, you can use the picture, no problem. Hope the cap has some benefit.
One of my clock is also near by the TV the other under my monitor. While working the last days i  not sure if i saw a short flicker or if it was only the seconds overflow. 
Yes, the biggest problem is that there is no indicator were we can see if the display make some "mistakes".
Think have to watch some boring films on TV so there is enough time to check the clock :-)

**Comment by popy2k14** [comment]
@UCaGk thx, i have now used your picture (forgot to make some).
Yeah, let's binge something. Also the weather here says -> you must binge :-)

**Comment by UCaGk** [comment]
Happy New Year everyone.
Just wanted to update you guys.
Since the recent changes didn't fix the flickering issue, I've been reverse engineering the Ulanzi watch for the past few weeks.
After that, I reverse all the changes I made previously (stepdown, shortcuts, removed parts) so the board was back to its factory state.
Then I made some new changes, removed more parts and added two cables so the watch now only works with USB power.
Now I'm waiting to see if the watch flickers or reboots.
I'll let you know when the issue is resolved.

**Comment by popy2k14** [comment]
@UCaGk Since i made the mod with the caps and disabled the esphome serial logging in yaml, it's stable for me.

Mod: https://www.reddit.com/r/homeassistant/comments/1grzksj/ulanzi_tc001_always_on_mod_battery_removal/

esphome disable serial logging:

```
...
# Enable logging and disable serial uart (with baudrate: 0)
logger:
  baud_rate: 0    
...
```

**Comment by UCaGk** [comment]
@popy2k14 
Nice to hear that it's working for you.
I wanted to take a closer look at the Ulanzi circuit to possibly build a DIY solution based on it that would then be compatible with Awtrix.
I see the advantage of my current solution is that you no longer need any extra components.
Hoping that it won't flicker or boot anymore now, will see...
If it works for a while, I'd be happy to send you a new photo.

**Comment by popy2k14** [comment]
@UCaGk Nice work!!! Looking forward to good news from your side.

**Comment by UCaGk** [comment]
So, think this should now run without rebooting and flickering, it looks stable since the last few days, hopefully it stays that way.

@popy2k14 
You can use the image for your side if you want.

![UlanziMod](https://github.com/user-attachments/assets/c358b774-ac41-40a5-b4d5-2915078565ab)

**Comment by popy2k14** [comment]
@UCaGk Wow, thx a lot for taking the time and reverse engineer the ulanzi clock!!!!
Is it stable up until now?

If so, i will use your picture and update my reddit thread.
Thx for permission to use it :-)

Will do so if i hear back from you.

**Comment by Naruto-kyun** [comment]
@popy2k14 i just did his mod, using other ground that i found more convenient (one from the chip remove on the left, one on the pins next to the usb) and for now it seems to work, dont know in long run tho.
Battery indicator show 87% which i found pretty funny.

**Comment by popy2k14** [comment]
thx for confirming. I will add this mod to the reddit thread soon.

**Comment by Naruto-kyun** [comment]
@popy2k14 12h later, it is still alive

**Comment by popy2k14** [comment]
@UCaGk thx for your method of the mod and @Naruto-kyun for confirming it works.

I have updated my reddit thread: https://www.reddit.com/r/homeassistant/comments/1grzksj/ulanzi_tc001_always_on_mod_battery_removal/

**Comment by Hypfer** [comment]
I've just successfully did the mod as described by @UCaGk

A few ideas that might be useful to people in the future:

To remove the front panel, you have to do the same as with any other glued front panel (e.g. a smartphone). Heat helps.
For that, I've used my 3d printer and let it rest on its front on the 60°C printbed for 30 minutes.

Then, I could use an ifixit (or similar) suction cup to easily remove the front.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/06cb244a-b41d-43a1-95ee-3df312c7c8a8" />

______

For the component removal, if desoldering is difficult (and/or you're a cretin), you can also just cut away the stuff in question with a small wirecutter. It might make sense to wear safety goggles for that.
It's probably a terrible idea and you can do lots of damage that way, but the people on youtube are doing it, so...
