### ISSUE TITLE
[BUG] half of bottom row pushed one pixel to the left

### ISSUE THREAD

**Issue by uuzi** [Blueforcer/awtrix3#556]
Half of the bottom most row of pixels ist pushed one pixel to the left after flashing. Tried flashing again, same result.

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: v0.96
![IMG_20240522_230447](https://github.com/Blueforcer/awtrix3/assets/947124/759e01f0-6faa-41e3-9b05-7c04360ec5a3)
![IMG_20240522_230442](https://github.com/Blueforcer/awtrix3/assets/947124/f741aad0-afca-48c5-bc91-190f56cfc252)

**Comment by Blueforcer** [comment]
You're the first one with this. So I assume this is a hardware fault. 
Flash the original firmware and see if it is persistent

**Comment by uuzi** [comment]
Will do and report back this evening.

**Comment by L1ttl3b4k3r** [comment]
> Will do and report back this evening.
> 
> I just checked and yes it seems like a hardware fault. I've contacted Ulanzi support, let's see what they say.

I recently encountered exactly the same issue. What was the reply of Ulanzi?
What was the cure?

**Comment by L1ttl3b4k3r** [comment]
Did you sent them pictures with the original firmware or with awtrix3 ?

**Comment by uuzi** [comment]
Just to be safe, I first returned to original firmware.
