### ISSUE TITLE
[BUG] Clock doesn't get adjusted with Timezone

### ISSUE THREAD

**Issue by w4mhi** [Blueforcer/awtrix3#563]
# Bug report
The clock in Bucharest shows 08:57 but should be 09:57 according the timezone.

## Describe the bug

I expect to selectthe timezone (like in the original firmware from Ulanzi) and the clock should adopt the timezone. The clock actually is behind with 1h and no way to adjust it.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: [ eg. v0.96 ]

## To Reproduce

Flash the firmware and wait for the clock in the Bucharest's timezone.

## Expected behavior
1. Timezone should be customizable in case of failure.
2. Timezone should be taken from a provider that has DST included.

Thank you!

**Comment by Blueforcer** [comment]
Have you read the documentation or even tried to access the awtrix web interface?

https://blueforcer.github.io/awtrix3/#/webinterface
