### ISSUE TITLE
[FEATURE REQUEST] Sensor "Bat_raw" in Homeassistant

### ISSUE THREAD

**Issue by calipposcout** [Blueforcer/awtrix3#568]
# Feature Request
Adding a sensor which reports the raw battery value (bat_raw) in Home Assistant

### Is your feature request related to a problem?
Since the used hardware has some issues reporting battery state, it would be good to use the raw battery values.

### Describe the solution / feature you'd like
A sensor, which reports the bat_raw value, which is contained in the MQTT-reported stats, would be fine.

![grafik](https://github.com/Blueforcer/awtrix3/assets/27622303/24020e60-c432-4bf8-a586-f98b37d77627)

**Comment by Blueforcer** [comment]
Most users doesn't need it.
Just create your own HA mqtt sensor, wich uses the raw bat value from the /stats topic.
