### ISSUE TITLE
MQTT ERR CNCT Loop

### ISSUE THREAD

**Issue by Samoht80** [Blueforcer/awtrix3#571]
I have the following error:
As soon as I connect the Ulanzi TC001 to my MQTT broker, the watch goes into a boot loop.

Restarts every time with the following text:
CHECK

ERR CNCT

I use software version 0.96. MQTT broker is installed as an adapter in iobroker (port 1883, username + password, without SSL)
I have the same error on other Ulanzi watches.

At home I use an adapter in iobroker that uses the http connection. I would like to take an additional watch with me to the office that is not on the home network.

**Comment by Blueforcer** [comment]
Dublicate of the pinned issue: https://github.com/Blueforcer/awtrix3/issues/165
