### ISSUE TITLE
[FEATURE REQUEST] Link to Icon Gallery

### ISSUE THREAD

**Issue by Andre1Becker** [Blueforcer/awtrix3#573]
Hi all,

It would be nice to see a direct link to the [LeMetric Icon Gallery](https://developer.lametric.com/icons) in the docs or even better, within the "Icons" tab on the Webinterface.

Cheers!

**Comment by daniel-simpson** [comment]
You can actually do this yourself, if you're willing to play around in the `DoNotTouch.json` file.

Note: back it up first!

Change the line starting with `  "raw-html-icon_html":` to

```json
"raw-html-icon_html": " <div id=\"iconcontent\"> <div id=\"form-con\"> <form> <label for=\"lametric-iconID\">Icon ID</label><br> <input type=\"text\" id=\"lametric-iconID\" name=\"lametric-iconID\"><br> <div class=\"button-row\"> <input class=\"btn\" type=\"button\" value=\"Preview\" onclick=\"createLametricLink()\"> <input class=\"btn\" type=\"button\" value=\"Download\" onclick=\"downloadLametricImage()\"> </div> </form> </div> <br> <br> <div id=\"icon-container\"> </div> <a href=\"https://developer.lametric.com/icons\" target=\"_blank\">Icon lists</a> </div>",
```

Not particularly pretty, but gets the job done!

![image](https://github.com/user-attachments/assets/94b74f55-42cc-402c-9af2-ec4e9cc83b61)

**Comment by Andre1Becker** [comment]
Works as expected! Nice!
