### ISSUE TITLE
[BUG] TMODE doesn't stick

### ISSUE THREAD

**Issue by pyrodex** [Blueforcer/awtrix3#574]
# Bug report

## Describe the bug

Setting TMODE via MQTT to 0 works but after a period, with no reboots, it defaults back to TMODE 1. Pushing the TMODE 0 via MQTT works and sets it. My experience has been usually after I set it for the day via MQTT to "fix it" and then come back to my office the next day it has reverted but the clock itself never rebooted nor was it asked to change via MQTT to TMODE 1.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: 0.96

## To Reproduce

* Set TMODE to 0 via MQTT
* Confirm TMODE is set via the clock and it reflects properly
* Come back to office, where clock is, next day and see TMODE visually has reverted back to TMODE 1
* Reset TMODE to 0 via MQTT
* Repeat

## Expected behavior

If I set TMODE 0 it should stick and be saved to the settings and not be reverted. 

## Screenshots

N/A

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

## Additional context

More than happy to pull any logs or debug to help troubleshoot this issue.

**Comment by Blueforcer** [comment]
There is no automatic setback. Make sure you doesn't have any Automation wich Sets it back. (Like a night mode flow or something like this)
