### ISSUE TITLE
[BUG] Awetrix turns off sometimes

### ISSUE THREAD

**Issue by BenAhrdt** [Blueforcer/awtrix3#580]
# Bug report
The device turns off the power.

## Describe the bug
Sometimes in the morning i see, that the device is powered off.
press the left and right button tuns it on. the device is continously on usb supply.

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: [ eg. v0.96 ]

**Comment by Blueforcer** [comment]
Then it's not enough power. The software is not able to turn off the device. There is no physical connection to the powerboard

**Comment by BenAhrdt** [comment]
But it is still on the usb an when i turn it on, it works without usb. => so the battery is full

**Comment by Blueforcer** [comment]
It's a hardware related issue, try another USB source, make sure you doesn't switch off the power supply over night etc.
 It's 100% impossible that the firmware can turn off the device.

**Comment by BenAhrdt** [comment]
OK. i will try.

**Comment by mod42** [comment]
I see the same. After some time, the clock switches off. Always connected via USB.

**Comment by ploro-it** [comment]
I have the same issue: when the clock is under 70% battery, it suddenly goes off, and I have to turn it on pressing the two buttons. But it only lasts a few minutes, until I recharge it to 100%. I don't think it is a software related bug, because I had this problem with both the old firmware and the new one

**Comment by Blueforcer** [comment]
There are different batches of the Ulanzi with different battery readings. 
Use the raw_bat value of the stats and set the min and max battery values in the dev.json to make the percentage display correct
