### ISSUE TITLE
[BUG] Day Of Week Color

### ISSUE THREAD

**Issue by FrankGiesecke** [Blueforcer/awtrix3#581]
# Bug report

## Describe the bug

If I understand the API docu, it should be possible to define a color for day of week marker using the keys "WDCA" and "WDCI" in the settings endpoint.

Unfortunately this has no effect.

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: [ eg. v0.96 ]

## To Reproduce

Send the following settings config in MQTT

```json
{
"WDCA": "#FF0000",
"WDCI": "#0000FF"
}
```

## Expected behavior

The current day should be represented in red, all other days in blue.

## Screenshots

-

## Logs

-

## Additional context

-

**Comment by EmEiBee** [comment]
I agree with that.
Almost all other commands in config also have no effect, such as SOM or DAT

**Comment by Blueforcer** [comment]
Works as it should.

```json
{
"WDCA": "#FF0000",
"WDCI": "#0000FF",
"SOM":false
}```
results in the correct behaviour:

![awtrix (2)](https://github.com/user-attachments/assets/fbfeaf66-00ce-42e6-843b-15f4e16fd762)

**Comment by EmEiBee** [comment]
... ... unfortunately not for me:
![img-2024-10-28-23-57-55](https://github.com/user-attachments/assets/6d296a52-a8a4-43b3-bae9-1972cde7ec57)

**Comment by Blueforcer** [comment]
> ... ... unfortunately not for me: 

its /settings not /settings/

thats why the messagetree looks different to mine:
![image](https://github.com/user-attachments/assets/0689d9a6-cfef-451d-a234-99e63eb518c3)

**Comment by EmEiBee** [comment]
> its /settings not /settings/

UFFF... Ok, you are right here... Then it works like expected...

So Q:
Why I have to use it without backslash at this point where others have to be with backslash?

![img-2024-10-29-00-04-36](https://github.com/user-attachments/assets/9cdfafb6-e8f8-4c71-975a-bf9f55718b92)

**Comment by Blueforcer** [comment]
This is also not the case here
Your Topic is like pixel/custom/HKV not pixel/custom/
