### ISSUE TITLE
[BUG] Icon Tab missing

### ISSUE THREAD

**Issue by bubiman** [Blueforcer/awtrix3#584]
# Bug report

## Describe the bug

The Icon Tab to download and install icon is missing. 
Yesterday I received my TC001 flashed it with version 0.96 and it was working fine. I could download icons yesterday but today the Icon Tab is simply no longer avaible. I tried to reboot the clock through iobroker, I turn the clock off and back on again the the arrow buttons but the Icon Tab is still missing

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: [ eg. v0.96 ]

## Screenshots

![image](https://github.com/user-attachments/assets/bbc0300f-3de2-42e5-a38b-461a6888b52b)

## Additional context

I can see and use the icons I have installed yesterday

![image](https://github.com/user-attachments/assets/8ed7c7c5-7aa0-449f-8425-2998d3a20224)

**Comment by udo1toni** [comment]
Maybe you messed up the DoNotTouch.json.
Afaik deleting the file and do a restart should create a new (default) file. Please be aware that you will lose some settings such as ntp server or a fixed ip.

**Comment by bubiman** [comment]
I haven`t touched the DoNotTouch.json. I have reset the clock with the button on the back and had to set up the clock again. For now it is working

**Comment by eku** [comment]
> Maybe you messed up the DoNotTouch.json.

The software itself is responsible for this, see also #549.
