### ISSUE TITLE
[INFO] Is it possible to update firmware ?

### ISSUE THREAD

**Issue by usky73** [Blueforcer/awtrix3#590]
I have a TC001, I did the firmware update few month ago.
My firmware is AWTRIX Light 0.70, it seems a little bit old. 
The link on web interface to the documentation is not working anymore.
I remember than flashing the firmware was a nightmare (might be due to the USB cable) I would like to avoid it again, and more than that, not loosing the setting.

I have an update menu on web interface & also home assistance

Is there a way to use it to update it ?
Where can I find the update file ?
To save config and import it on awtrix3 ?

**Comment by klein0r** [comment]
> The link on web interface to the documentation is not working anymore.

The project has been renamed to Awtrix 3 and the urls have changed. The web flasher is available here:

https://blueforcer.github.io/awtrix3/#/flasher

**Comment by Blueforcer** [comment]
Where did you find the old link? I thought I had replaced them all.

**Comment by usky73** [comment]
The link came from the web interface of the firmware - AWTRIX Light 0.70

**Comment by usky73** [comment]
> > The link on web interface to the documentation is not working anymore.
> 
> The project has been renamed to Awtrix 3 and the urls have changed. The web flasher is available here:
> 
> https://blueforcer.github.io/awtrix3/#/flasher

Then no other choice than flash it again, correct ?

**Comment by Blueforcer** [comment]
You can download the bin file from the repo releases and upload it in the update Menü. But if it's too old you need to reflash it

**Comment by usky73** [comment]
ok thanks.

**Comment by usky73** [comment]
last dummy question, where is this bin file ?

**Comment by Blueforcer** [comment]
https://github.com/Blueforcer/awtrix3/releases
