### ISSUE TITLE
[BUG] mqtt topic published under: /notify does not display

### ISSUE THREAD

**Issue by sjetzer** [Blueforcer/awtrix3#592]
# Bug report (?)

## Describe the bug

Hello,
The topic published under: awtrix_06cf08/notify does not display on the TC001 but 
if published under: awtrix_06cf08/custom/test  it's works well! 

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix (TC001)
  - awtrix3 version: [ 0.96 ]

## To Reproduce
HASS automation Not OK:
`action: mqtt.publish
metadata: {}
data:
  topic: awtrix_06cf08/notify
  payload: >-
    {"icon": "23634","text":
    "{{states('sensor.sensor_soil_moisture_2')}} % ,  "duration": 20 }  alias: Soil 02`

HASS automation OK:
`action: mqtt.publish
metadata: {}
data:
  topic: awtrix_06cf08/custom/soil
  payload: >-
    {"icon": "23634","text":
    "{{states('sensor.sensor_soil_moisture_2')}} % ,  "duration": 20 }  alias: Soil 02`

## Screenshots
The messages are transmitted well (check with mqtt explorer)
![image](https://github.com/user-attachments/assets/9d66ca6d-e5ab-4c5e-b138-9eac8fe796b3)

A clue ? ;-)
Thx

**Comment by Blueforcer** [comment]
Can you post the full json from MQTT explorer please?
