### ISSUE TITLE
[BUG] flows unavailable

### ISSUE THREAD

**Issue by vclementTogo** [Blueforcer/awtrix3#596]
The website to use to add APPS is not available.

Is there a problem with https://flows.blueforcer.de/ ?
Or is it on another website ?

Best Regards,

**Comment by Blueforcer** [comment]
My VPS provider has currently datacenter issues.
https://contabo-status.com/

**Comment by vclementTogo** [comment]
Thanks for the info,
Wish you the best during this storm.
