### ISSUE TITLE
[FEATURE REQUEST] Serve Awtrix 3 via SSL

### ISSUE THREAD

**Issue by mkotek** [Blueforcer/awtrix3#608]
# Feature Request
Enable serving Awtrix via HTTPS

### Is your feature request related to a problem?
I am serving HA in my local network using SSL. Would it be possible to serve Awtrix also via HTTPS instead of HTTP? 

### Describe the solution / feature you'd like
This way, it would be possible to serve pages like LiveView inside HA 

### Describe alternatives you've considered
While it is possible to serve HA via HTTP internally and via HTTPS externally, I find it cumbersome to make sure everything works as expected, no matter if one is on internal or external network and HTTPS is better when applied everywhere.

I have also tried to configure Proxy Manager to serve page as HTTPS but I am getting Error 500 from Awtrix this way.

**Comment by Blueforcer** [comment]
Its not possible due low ram resources. SSL certificates needs many resources
