### ISSUE TITLE
[FEATURE REQUEST] Remove/suspend some default apps

### ISSUE THREAD

**Issue by lucaberti** [Blueforcer/awtrix3#610]
I'd like to be ablet o remove some standard apps (information) from the cycle.

Right now the default information cycle is given. It sould be possible to change it from web interface.

**Comment by Blueforcer** [comment]
You can remove them via the official smartphone App, via API or with the Onscreen menu.

**Comment by lucaberti** [comment]
That's great! Still I'd like to be able to costumize the clock by web interface.
