### ISSUE TITLE
[FEATURE REQUEST] HTTPS support

### ISSUE THREAD

**Issue by davey400** [Blueforcer/awtrix3#614]
# Feature Request
### Is your feature request related to a problem?
I am using my Ulanzi device with your brilliant Awtrix software and controlling it via Home Assistant (MQTT).
I would like to integrate the http://<ip>/fullscreen view into my Home Assistant (HA) dashboard. However, modern browsers no longer allow embedding HTTP content into an HTTPS page, which presents an issue.

### Describe the solution / feature you'd like
I would like Awtrix to support HTTPS for the fullscreen page, or ideally for all pages. A self-signed certificate would be sufficient.
In the long term, automatically requesting certificates through ACME or SCEP would be an amazing feature. ;)

### Describe alternatives you've considered
The only alternative I've considered is using a reverse proxy on a separate instance to convert the current HTTP content to HTTPS. Another option would be switching my HA instance to HTTP, but that feels like a step backwards.

**Comment by Blueforcer** [comment]
Theres not enoug recources to implement that, sorry. 
But there are user project to use mqtt for screensharing in HA. Have a look at my discord.
