### ISSUE TITLE
Switch off charging LED

### ISSUE THREAD

**Issue by Mkyuu10** [Blueforcer/awtrix3#615]
# Feature Request

### Is your feature request related to a problem?
I have a Pixel Clock in my bedroom, where I like to have absolute darkness at night. I therefore switch off the clock matrix (automatically) at night. Unfortunately, the LED next to the USB port stays on and lights up the room.

### Describe the solution / feature you'd like
I would like to have the option of switching the LED off permanently or together with the matrix.

### Describe alternatives you've considered
Unfortunately, masking the LED does not help completely and can only darken it, as the plastic of the clock is translucent.

**Comment by Blueforcer** [comment]
Its not possible to switch it off because its controlled by the powerboard, not the ESP
