### ISSUE TITLE
MQTT: topText / hold dont work?

### ISSUE THREAD

**Issue by EmEiBee** [Blueforcer/awtrix3#616]
Hello there,

could I get some help please?
I send the following to the watch (awtrix 0v96) via MQTT (Explorer):

```
{
"text":"HEATING FAULT!",
"color":"#FF0000",
"topText":true,
"hold":true
};

```
I assumed that -topText- would display the message immediately and suppress all apps currently running, and that -hold- would display it until it was acknowledged or the "alarm" app was deleted.
The text is displayed in red, but only at the end of all running apps (time, date, outside temperature, outside humidity).

Am I misunderstanding something here???

**Comment by Blueforcer** [comment]
Toptext only belongs to the current data, so the text will be shown over a icon or drawing.

I assume you're sending it to the /custom API. Send it to /notify. This is a notification and will be displayed as a top layer over everything.

**Comment by EmEiBee** [comment]
Ohhhh ^^ Yes, that makes sense now that you mention it...
Thank you for this tip! I somehow didn't have it on my radar...

Greetz
Micha

**Comment by Blueforcer** [comment]
Der MQTT explorer zeigt dir wo der Fehler ist. Das Semikolon am Ende muss weg. Sonst ist die Json nicht valide

**Comment by Blueforcer** [comment]
https://blueforcer.github.io/awtrix3/#/api?id=dismiss-notification

**Comment by EmEiBee** [comment]
Danke! Auf die Idee nach dem Wort "dismiss" zu suchen, bin ich gar nicht gekommen. 
Sollte man vielleicht mal mit in die Beschreibung von "hold" mit reinnehmen...

**Comment by EmEiBee** [comment]
"loopSound" funktioniert weder mit der direkten Übergabe von rtttl-Daten, noch mit unter /Melodies abgelegten und via "sound" aufgerufenen rtttl-Dateien.

**Comment by EmEiBee** [comment]
hmmm...
Ist das nun ein Bug oder bin ich zu blöd?

**Comment by EmEiBee** [comment]
Dann verstehe ich es nicht... 
Ich setze mal ....
`/pixel/notify {"sound":"rtttl_Sirene","loopSound":true}`
An der Stelle würde ich davon ausgehen, dass hier die Loop, ähnlich wie 'hold', so lange dudelt, bis das notify quittiert wird. Das passiert nicht. Zudem löscht sich das notify selbst. Es läuft nur so lange, wie die Anzeigezeit der anderen App's gesetzt ist. Ist diese 5 Sekunden, dann dudelt es auch 5 Sekunden, gefolgt von der ersten App in der Reihe und zudem am Ende nicht mehr vorhanden.
Es funktioniert also nur so:
`/pixel/notify {"sound":"rtttl_Sirene","loopSound":true,"hold":true}`
Das ist nach meiner, natürlich unmaßgeblichen, Meinung irgendwie doppelt gemoppelt. Oder verstehe ich hier irgendwas falsch?

**Comment by Blueforcer** [comment]
nö,
warum sollte der notification sound weiter loopen, wenn die notification beendet ist?
So hat doch jeder die Möglichkeit es so anzupassen wie es ihm gefällt. 
Ewige notification mit ewigem gedudel, oder ewige notification mit einmal gedudel.

**Comment by EmEiBee** [comment]
... hmmmm ... Von der Seite habe ich das noch nicht betrachtet; da magst Du recht haben...
Ok, ist so dann verstanden worden. Danke dafür! Habe ich mir gleich mal als Notiz dran gehängt, damit ich es nächstes Jahr auch noch weiß ;)

EDIT:
Es wäre schön, wenn man bei LoopSound noch eine Pausenzeit angeben könnte, bestenfalls anstatt 'true' einen Wert größer 0 in z.B. 'Pause  * 100ms'. Man könnte es sich zwar in den rtttl-sound mit einbauen am Ende, aber dann bräuchte man oft von einem Sound gleich zwei oder mehr Versionen mit unterschiedlichen Pausen am Ende (funktioniert das überhaupt? Noch nicht probiert); auch nicht schön...

**Comment by Blueforcer** [comment]
Ich notiers mal, denke aber das es nicht so einfach umzusetzen ist.
Ich mach hier mal dicht, da sich das Ursprungs issue ja schon länger erledigt hat
