### ISSUE TITLE
[BUG] WebGUI - menue broken 

### ISSUE THREAD

**Issue by EmEiBee** [Blueforcer/awtrix3#623]
System is alive but WebGUI - menue is broken

The error occurred overnight.
The menu shows repeating menu items with some menu items missing

![firefox_wAdu9qz1Oa](https://github.com/user-attachments/assets/6cdfca2e-da67-4b78-a66f-3f0ac0ba2ab4)
( Animated GIF when triggering a forced refresh [SHIFT F5] )

  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: 0.96

Multiple resets of the watch did not help. 
Reloading or even forcing the browser to reload does not help.
Same issue with all available browser.
The following duplicate, red boxed entries have no function.
![img-2024-10-29-09-00-20](https://github.com/user-attachments/assets/5e48ff59-0236-4ec6-861f-ac3b18e5f681)

The system itself works, is responsive and exchanges data via MQTT without errors.

**Comment by eku** [comment]
Duplicate to #549. Next time use the search function.

**Comment by EmEiBee** [comment]
> Next time use the search function.

There is no need to explicitly mention the search function. The search function only helps if the double has used exactly the words that you would use to describe the problem. An AI that recognizes what I am looking for, even if the search terms I used are not present in the target, does not yet exist (thank God).
