### ISSUE TITLE
[BUG] Batterylevel is very unprecise on Ulanci TC001

### ISSUE THREAD

**Issue by MeisterQ** [Blueforcer/awtrix3#624]
The batterylevel is very unprecise. If you charge it up to full, it shows 98% on api,

If you leave it running on battery, it will shut off on 48%.

I know ESPs adc isnt very precise, but is there a way to fix it?

Running on awtrix 0.96 on Ulanzi TC001

**Comment by Blueforcer** [comment]
The power management and the battery is also very cheap.

You can tweak it with the min and max values in the dev.json.
You will get the actual raw value from the stats topic

**Comment by MeisterQ** [comment]
> The power management and the battery is also very cheap.
> 
> You can tweak it with the min and max values in the dev.json. You will get the actual raw value from the stats topic

Where is the dev.json to find at?

**Comment by MeisterQ** [comment]
Thank you. Worked
