### ISSUE TITLE
[FEATURE REQUEST] Does AWTRIX3 supports manual time installation and custom NTP-servers URLs?

### ISSUE THREAD

**Issue by AlexanderKhudoev** [Blueforcer/awtrix3#625]
# Feature Request

### Is your feature request related to a problem?

My Ulanzi TC001 on the standard firmware started lagging 2 minutes behind the main internet time. Is there any possibility to set the time manually or specify a custom NTP server in AWTRIX3?

### Describe the solution / feature you'd like

Feature to manually setup time (hours and minutes) and custom NTP server urls.

### Describe alternatives you've considered

-

### Additional context

![image](https://github.com/user-attachments/assets/b72baa12-8ce9-4207-aee9-c86925d52df3)

**Comment by Blueforcer** [comment]
You can only set the NTP server and Timezone in AWTRIX. no manual time.
