### ISSUE TITLE
[BUG]is something else happening here or is awtrix dead?

### ISSUE THREAD

**Issue by warp735** [Blueforcer/awtrix3#628]
50 open points and the last update from March? I still have two daily freezing Ulanzi's and unfortunately nothing happens here at all. I wish I'd known beforehand that it would go to sleep again so quickly.

**Comment by warp735** [comment]
Here on page 1 alone I count 10 bugs. Why should I report something here if nothing has happened for almost a year?
Many people report frozen Ulanzis in the ioBroker forum. I thought this had already been reported.

**Comment by Blueforcer** [comment]
You need to read the issues, most of them are feature requests or user errors.

**Comment by davey400** [comment]
@warp735: to put things in perspective: Happy user here. 
No issue. No freezes. 
Had a question/FR. Was answered within a decent timeframe.
@Blueforcer thank you from all the silent happy users. ;)

**Comment by Blueforcer** [comment]
@davey400 Thank you very much. 
And to be clear, Awtrix 3 is of course not dead, there are just too few changes for an update to be worthwhile.

**Comment by m-wo** [comment]
I'm also facing constant reboots with my Ulanzi Pixel Clock on Awtrix 0.96 - could you give the PR https://github.com/Blueforcer/awtrix3/issues/564 a look, to at least be able to better debug restart reasons?

**Comment by Blueforcer** [comment]
> I'm also facing constant reboots with my Ulanzi Pixel Clock on Awtrix 0.96 - could you give the PR https://github.com/Blueforcer/awtrix3/issues/564 a look, to at least be able to better debug restart reasons?

Here's the wrong issue for that.
The debug method doesn't help so far, as you can see from the creator, the output was meaningless. Furthermore random restarts only happen to <1% of the users. And we're speaking of thousands of total users. 
Unfortunately I'm unable to reproduce a single reboot for months. So currently I assume an hardware issue.

**Comment by Blueforcer** [comment]
> > I'm also facing constant reboots with my Ulanzi Pixel Clock on Awtrix 0.96 - could you give the PR https://github.com/Blueforcer/awtrix3/issues/564 a look, to at least be able to better debug restart reasons?
> 
> Here's the wrong issue for that.
> The debug method doesn't help so far, as you can see from the creator, the output was meaningless. Furthermore random restarts only happen to <1% of the users. And we're speaking of thousands of total users. 
> Unfortunately I'm unable to reproduce a single reboot for months. So currently I assume an hardware issue.

If you can tell me how to reproduce it, I'm happy to investigate further.

**Comment by eku** [comment]
> The debug method doesn't help so far, as you can see from the creator, the output was meaningless.

I will not leave it uncommented, as I am not entirely comfortable with this. The reason for the restart depends on how it is used and the given technological conditions.

At my clock, the restart happened due to a software problem. It is essential to note that the specific line of code responsible for the issue cannot be deduced from the information provided. Despite this, I have managed to discover some evidence and have mentioned it several times in this context.

Concerning power issues, reliable detection would be of great importance.

**Comment by Blueforcer** [comment]
Where? Please post the comment links or better the code function
