### ISSUE TITLE
[FEATURE REQUEST] Direct Pixel Control via MQTT (matrix Property)

### ISSUE THREAD

**Issue by akunia** [Blueforcer/awtrix3#629]
Hi,
Here below my request generated by ChatGPT (I'm dot a developer):

I would like to request the implementation of a feature that allows direct pixel manipulation on the AWTRIX display through MQTT. Specifically, this feature could be implemented as a matrix property in MQTT payloads, enabling users to define the position and color of individual pixels programmatically.

For example:

```
{
  "duration": 5,
  "matrix": [
    {"x": 0, "y": 0, "color": "#FF0000"},
    {"x": 1, "y": 0, "color": "#00FF00"},
    {"x": 2, "y": 0, "color": "#0000FF"}
  ]
}
```
Use Case: This feature would open up new possibilities for creative and dynamic displays, such as:

Displaying custom animations or progress bars.
Visualizing real-time data, like energy usage or temperature trends, directly as a grid of colors or patterns.
Allowing greater control over the AWTRIX display for users who want to go beyond text and icons.
Benefits:

Enhanced Customization: Users can create dynamic, pixel-perfect displays for specific use cases without relying on pre-designed icons.
Compatibility: This aligns AWTRIX’s functionality with modern LED matrix frameworks, which often support pixel-level control.
Community Engagement: This feature could attract more users and contributors who are looking for highly flexible, programmable displays.
Proposed Implementation:

Add a matrix field to the custom MQTT payload specification.
Allow the matrix array to define:
x: Horizontal position (0–7 for an 8x8 matrix).
y: Vertical position (0–7 for an 8x8 matrix).
color: Pixel color in HEX format (e.g., #FF0000 for red).
Combine this property with duration and icon/text fields, ensuring backward compatibility with existing functionality.
Example Payload: To display a single row of blue pixels:

```
{
  "duration": 5,
  "matrix": [
    {"x": 0, "y": 6, "color": "#0000FF"},
    {"x": 1, "y": 6, "color": "#0000FF"},
    {"x": 2, "y": 6, "color": "#0000FF"}
  ]
}
```
Potential Challenges:

Compatibility with existing rendering logic.
Memory or processing constraints for handling real-time pixel data.
Conclusion: Direct pixel control would be a highly valuable addition to AWTRIX’s feature set, enabling advanced display options for power users and developers. This would also keep AWTRIX competitive with alternative smart LED matrix solutions.

Thank you for considering this request! Please let me know if I can provide further details or examples.

**Comment by Blueforcer** [comment]
That sounds a lot like ChatGPT :)

but already exists:
https://blueforcer.github.io/awtrix3/#/api?id=drawing-instructions
