### ISSUE TITLE
[FEATURE REQUEST] Multiple Icons

### ISSUE THREAD

**Issue by A380Coding** [Blueforcer/awtrix3#634]
# Feature Request

### Is your feature request related to a problem?

no

### Describe the solution / feature you'd like

Currently one Icon can be displayed per app.
Support for displaying multiple icons per app next to each other.
Is there any technical restriction, like memory?

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by Blueforcer** [comment]
Yes, not enough RAM to use two or more renderer
