### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by Grosscoder** [Blueforcer/awtrix3#638]
# Feature Request

### Is your feature request related to a problem?

no

### Describe the solution / feature you'd like

it should support hebrew letters by using UTF-8 and direction rtl.

### Describe alternatives you've considered

null

### Additional context

nothing

**Comment by Blueforcer** [comment]
UTF8 encoding is already implemented.
But the font doesn't contain these letters.
Unfortunately there isn't enough space in the font to add these.
