### ISSUE TITLE
[BUG] Random flickering and color changes (noise)

### ISSUE THREAD

**Issue by mymmrac** [Blueforcer/awtrix3#639]
Hi, is my Ulanzi TC001 broken or I am doing something wrong?

I have reinstalled this firmware multiple times and each time I see random pixels flickering and changing colors, most noticeable when display has red color on it, for me seems like some memory issue, but I don't know how to validate that, also this happens right after start, so I don't think this is something related to memory leaking (RAM seems to have ~138k free bytes).
Note: When I bought it was working fine, this started after 2–3 days or using it
Note 2: In http://<ip>/screen it shows correct image

Any ideas why this may happen?

![image](https://github.com/user-attachments/assets/28b00ac5-a723-4db7-8347-472727147c26)

**Comment by mymmrac** [comment]
I suppose this may happen because one pixel in the display is dead (at least seems like dead)

![image](https://github.com/user-attachments/assets/b585dc30-e50b-47ae-af36-5e4368b1606f)

**Comment by Blueforcer** [comment]
That's a hardware issue.

**Comment by Blueforcer** [comment]
That's a hardware issue. Try to get a replacement

**Comment by kusold** [comment]
This thread helped me. I opened my clock and immediately flashed awtrix3 onto it, so I was unsure if it was hardware or firmware.

For future visitors, you can set the background color to white with:

```
curl --request POST \
  --url http://${CLOCK_IP}/api/moodlight \
  --header 'content-type: application/json' \
  --data '{"brightness":150,"color":"#FFFFFF"}'
```

When I send that command repeatedly, I always get white up until the same dead pixel and then after that the colors vary.
