### ISSUE TITLE
[BUG] Download icon not working 404

### ISSUE THREAD

**Issue by galadril** [Blueforcer/awtrix3#642]
# Bug report

## Describe the bug
After flashing, there is no issue downloading icons via the website. But after a couple of day the download button stopped working and returns 404 or 500 errors.

This happened 3 times now, and i then re-flash AWTRIX3 cleanly, and reconfigure and than everything worksagain.
But after a couple of days i have the same issue again.

## Additional information
- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - awtrix3 version: [ eg. v0.96 ]

## Screenshots
![image](https://github.com/user-attachments/assets/30f6bcc9-44a2-4f74-b4b0-cf05fc1183af)

![image](https://github.com/user-attachments/assets/c8c19ced-d8ba-47e3-a19e-3c3d041b9c6d)

**Comment by eku** [comment]
Your browser does the download, not AWTRIX. 
I see you are behind a proxy. You may want to check your network.

**Comment by galadril** [comment]
mm i see already like 3 topics on this, ill close mine

**Comment by Blueforcer** [comment]
Please check this firmwareversion for more feedback
https://github.com/Blueforcer/awtrix3/issues/362#issuecomment-2069952551
