### ISSUE TITLE
How to change from dynamic IP-address to static IP-address

### ISSUE THREAD

**Issue by salabim** [Blueforcer/awtrix3#643]
I love the awtrix3 project (running on an Ulanzi clock).
Unfortunately, the IP address changes from time to time, making it difficult for me to ensure a stable connection with my Raspberry PI.
Is there a way to change to a static IP address?

**Comment by Blueforcer** [comment]
yes, open the webinterface and got to network.

**Comment by salabim** [comment]
Great. Thank you.
