### ISSUE TITLE
[QUESTION] How to enable snow

### ISSUE THREAD

**Issue by julius-d** [Blueforcer/awtrix3#652]
# Not possible to enable snow effect

Thank you very much for this awsome project.

## Describe the bug

I wanted to enable the nice snow effect  on my Awtrix 3, just like last year.
But I failed to do so.

I created a `/dev.json` file and tried
`  "let_it_snow": true` and also ` "background_effect": "Snow"`
so my current   `/dev.json` is
```json
{
  "let_it_snow": true,
  "background_effect": "Snow"
}
```
I also rebooted multiple times.
But there is no snow animation.

## Additional information

- Devices involved:
  - Model: Ulanzi Smart Pixel Uhr 2882
  - awtrix3 version: AWTRIX 3 **0.97**

Thank you very much and a merry christmas ☃️

**Comment by Blueforcer** [comment]
This changed in v0.95 from mid year.
Use the settings API with the OVERLAY key

**Comment by julius-d** [comment]
Thank you very much for your help. 

I just discovered that I can enable the snow effect also via the Android app. That is nice!
